const fs = require('fs')

const colors = require('./colors.js')

module.exports = function cli(args) {
  if (!(args[2] && args[3])) return console.log('Please choose an input file and an output directory, e.g. `fluentui-react-teams-theme theme-config.json ./theme`')

  console.log('[Generating theme…]')

  const config = JSON.parse(
    fs.readFileSync(args[2])
  )

  const siteVariables = colors(config)

  console.log('[Writing theme…]')

  fs.writeFileSync(
    `${args[3]}/react-teams-theme.js`,
    `// === === === === === ===
// DON’T EDIT THIS FILE DIRECTLY.
// This file is generated by @fluentui/react-teams theme script;
// === === === === === ===

export default ${
      JSON.stringify(siteVariables, null, 2)
    }`
  )

  fs.writeFileSync(
    `${args[3]}/react-teams-theme.d.ts`,
    `
    import { ThemeInput } from "@fluentui/styles";
    declare const _default: ThemeInput;
    export default _default;`
  )
  console.log('[Done.]')
}
